### ISSUE TITLE
Testing SemanticKITTI with unlabels pc returning all 0's in labels - am I looking in the wrong place?

### ISSUE THREAD

**Issue by ThysEmiel** [mellody11/RandLA-Net-Pytorch-New#1]
Is there any future where you add a test run for semanticKITTI testing data? 

You're are currently using validation which has labels in it as the TEST_DATASET/TEST_DATALOADER. This does not represent testing as it gets put in with the actual labels and not with a list of 0's. I'm struggling to get testing to work myself. 

Whenever I try and test the model with unlabeled pointclouds it seems to not even change the labels on the output. These remain 0 even when a min_possibility of 0.5 is reached over the whole testing dataset. Am I wrong to look in the labels on the output? Am I suppose to look somewhere else?

**Comment by mellody11** [comment]
Hi, thanks for your attention to the reimplementation.

1. I have not provided the testing code yet, but it will come soon in next few days. You can also follow the testing code in my another [repository](https://github.com/mellody11/SQN-Pytorch/blob/master/test_SemanticKITTI.py) and modify it to suit the RandLA testing(I will also write the testing code in this way). Because the testing code is similar in both papers.

2. I actually only evaluate the model on the validation dataset. 

3. As for the problem you mentioned, I don't know what changes you have make to the code. 
   Did you specify a check point path during testing?
   If you feed a list of full 0 as test labels to the network, maybe in [this](https://github.com/mellody11/PCAM-With-RandLA-Net/blob/6bd974545ad10564eaf99bf0e40374a8833a8016/RandLANet.py#L412) function the code will ignore your 0's label.

**Comment by mellody11** [comment]
> Is there any future where you add a test run for semanticKITTI testing data?
> 
> You're are currently using validation which has labels in it as the TEST_DATASET/TEST_DATALOADER. This does not represent testing as it gets put in with the actual labels and not with a list of 0's. I'm struggling to get testing to work myself.
> 
> Whenever I try and test the model with unlabeled pointclouds it seems to not even change the labels on the output. These remain 0 even when a min_possibility of 0.5 is reached over the whole testing dataset. Am I wrong to look in the labels on the output? Am I suppose to look somewhere else?

Hi, ThysEmiel.

I have released the test code for semantickitti, but I have not test my model and generate the predicted label yet, because It will spend some time while voting.

You can try the test code testing you model and I think the code should work correctly.

Remenber to modify the check point path before testing or the code would raise an error.

Good luck to you.
