### ISSUE TITLE
visualization 

### ISSUE THREAD

**Issue by jia1047** [mellody11/RandLA-Net-Pytorch-New#13]
I used the visualization code you previously provided to others, but when I used CC, the visualization result was blank and I don't know what's going on

![image](https://github.com/mellody11/RandLA-Net-Pytorch-New/assets/149373191/202493be-a297-41f2-b28b-9e30151fc0e7)
![e78ff0f1f9442558e868c35ca0eee94](https://github.com/mellody11/RandLA-Net-Pytorch-New/assets/149373191/a97893c2-a26f-4230-a2b5-fd8a78ebb58c)

**Comment by mellody11** [comment]
This may be caused by the representation range of colors. You should determine whether the representation range of colors is [0,255] or [0,1] in CC.

**Comment by jia1047** [comment]
May I ask if I have used the visualization code you previously sent to someone else, which is writePly (os. path. coin (LOG-DIR, 'val_preds', name), [xyzrgb, preds, labels], ['x', 'y', 'z', 'red', 'green', 'blue', 'pred', 'label']), and its visualization results are the same as original_ply's visualization results. I have since modified the code and wrote two writePly codes. I want to obtain the visualization of real labels and predicted labels, but the visualization results of these two are the same. All are consistent, consistent with writePly (os. path. coin (LOG-DIR, 'val_preds', name), [xyzrgb, preds, labels], The visualization results obtained from ['x ',' y ',' z ',' red ',' green ',' blue ',' pred ',' label '] and original_ply are consistent. May I ask how your visualization code is specifically written? Can you obtain visualization of real labels and visualization of predicted labels
![图片](https://github.com/mellody11/RandLA-Net-Pytorch-New/assets/149373191/fbff9b88-a255-4630-9c9c-3a5e46645254)

**Comment by mellody11** [comment]
It is foreseeable for the results to be consistent, because the `rgb` attribute is the same in your two ply files. As a result, if you directly visualize them, they are showing the same color.

if you want to visual the predicted result and gt like the following picture, you must map the predicted indices and gt indices to some specific colors and replace the `rgb` attribute then save as new ply files.
![1](https://github.com/mellody11/RandLA-Net-Pytorch-New/assets/74829174/a5396070-df14-4a04-b900-6012f82547df)
